apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  annotations:
    "nodeName": "k8s-master-ubuntu1" 
spec:
  containers:
  - name: nginx
    image: docker.io/library/nginx:alpine
    ports:
    - containerPort: 80
