---
apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf
extenders:
- urlPrefix: "http://127.0.0.1:9999/pod-annotations-scheduler"
  filterVerb: filter
  enableHTTPS: false
  nodeCacheCapable: true
  ignorable: false
